### ISSUE TITLE
Debug launch configuration empty on cursor

### ISSUE THREAD

**Issue by N-Demir** [pulumi/pulumi-vscode-tools#13]
### What happened?

Pulumi debug launch configuration is empty when trying to debug on cursor. I expected the `pulumi up` and `pulumi preview` launch configs but without them the debugging extension is not usable?

### Example

![Image](https://github.com/user-attachments/assets/1480d854-5928-4bd8-9161-a29e241809e7)

### Output of `pulumi about`

```
(.venv) ndemir@Mac my-virtual-machine % pulumi about
CLI          
Version      3.134.1
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME          VERSION
resource  azure-native  2.64.3
language  python        unknown
resource  random        4.16.6
resource  tls           4.11.1

Host     
OS       darwin
Version  15.0
Arch     x86_64

This project is written in python: executable='/Users/ndemir/engineer/splatter/my-virtual-machine/venv/bin/python' version='3.12.4'

Current Stack: N-Demir/my-virtual-machine/dev

TYPE                             URN
pulumi:pulumi:Stack              urn:pulumi:dev::my-virtual-machine::pulumi:pulumi:Stack::my-virtual-machine-dev
pulumi:providers:pulumi          urn:pulumi:dev::my-virtual-machine::pulumi:providers:pulumi::default
pulumi:providers:tls             urn:pulumi:dev::my-virtual-machine::pulumi:providers:tls::default_4_11_1
pulumi:pulumi:StackReference     urn:pulumi:dev::my-virtual-machine::pulumi:pulumi:StackReference::N-Demir/infrastructure/dev
tls:index/privateKey:PrivateKey  urn:pulumi:dev::my-virtual-machine::tls:index/privateKey:PrivateKey::ssh-key
pulumi:providers:azure-native    urn:pulumi:dev::my-virtual-machine::pulumi:providers:azure-native::default_2_64_3


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/N-Demir
User           N-Demir
Organizations  N-Demir
Token type     personal

Dependencies:
NAME                 VERSION
pip                  24.2
pulumi_azure_native  2.64.3
pulumi_random        4.16.6
pulumi-tls           4.11.1
setuptools           75.1.0
wheel                0.44.0

Pulumi locates its logs in /var/folders/56/7gjpxtt563n3q7bs3m3zxtlh0000gn/T/ by default
(.venv) ndemir@Mac my-virtual-machine % 
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by EronWright** [comment]
@N-Demir are you saying that the list of automatic debug configurations is empty?  Here's a couple of solutions:
1. Add the Pulumi project folder as a VSCode workspace folder (Add Folder...).  The debugging extension performs a "shallow" search (not "deep") of the workspace folders to find Pulumi projects.
2. Create a launch configuration manually into launch.json, as described [here](https://github.com/pulumi/pulumi-vscode-tools?tab=readme-ov-file#create-a-launch-configuration).

Let us know if these solutions don't work for you, and thanks for trying out the new extension.
